/*
 * Copyright (c) 2026 Mark Pollack
 *
 * Licensed under the Business Source License 1.1 (BSL).
 * See the LICENSE file in the repository root for the full license text.
 */

package io.github.markpollack.journal.event;

import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Records a code patch/diff generated by an agent.
 * This is the most common git event - agents generate patches before committing.
 *
 * @param timestamp when the patch was generated
 * @param baseBranch base branch/ref (e.g., "main", "abc123")
 * @param fileChanges files modified in this patch
 * @param linesAdded total lines added across all files
 * @param linesRemoved total lines removed across all files
 * @param patchContent optional full unified diff content
 */
public record GitPatchEvent(
        Instant timestamp,
        String baseBranch,
        List<FileChange> fileChanges,
        int linesAdded,
        int linesRemoved,
        String patchContent
) implements GitEvent {

    /** Compact constructor for defensive copy of fileChanges. */
    public GitPatchEvent {
        fileChanges = List.copyOf(fileChanges);
    }

    @Override
    public String type() {
        return "git_patch";
    }

    /**
     * Creates a patch event with computed line counts.
     *
     * @param baseBranch the base branch this patch is against
     * @param changes the file changes in this patch
     * @return a new GitPatchEvent
     */
    public static GitPatchEvent of(String baseBranch, List<FileChange> changes) {
        int added = changes.stream().mapToInt(FileChange::linesAdded).sum();
        int removed = changes.stream().mapToInt(FileChange::linesRemoved).sum();
        return new GitPatchEvent(Instant.now(), baseBranch, changes, added, removed, null);
    }

    /**
     * Creates a patch event with full diff content.
     *
     * @param baseBranch the base branch this patch is against
     * @param changes the file changes in this patch
     * @param patchContent the full unified diff content
     * @return a new GitPatchEvent
     */
    public static GitPatchEvent withPatch(String baseBranch, List<FileChange> changes, String patchContent) {
        int added = changes.stream().mapToInt(FileChange::linesAdded).sum();
        int removed = changes.stream().mapToInt(FileChange::linesRemoved).sum();
        return new GitPatchEvent(Instant.now(), baseBranch, changes, added, removed, patchContent);
    }

    @Override
    public Map<String, Object> toMap() {
        var map = new LinkedHashMap<String, Object>();
        map.put("base_branch", baseBranch);
        map.put("files_changed", fileChanges.size());
        map.put("lines_added", linesAdded);
        map.put("lines_removed", linesRemoved);
        if (patchContent != null) {
            map.put("patch_content", patchContent);
        }
        return map;
    }

    /**
     * Represents a single file change in a patch.
     *
     * @param path file path relative to repository root
     * @param changeType the type of change (ADDED, MODIFIED, DELETED, RENAMED)
     * @param linesAdded lines added in this file
     * @param linesRemoved lines removed in this file
     */
    public record FileChange(
            String path,
            ChangeType changeType,
            int linesAdded,
            int linesRemoved
    ) {
        /** The type of change made to a file. */
        public enum ChangeType {
            ADDED,
            MODIFIED,
            DELETED,
            RENAMED
        }

        /** Creates a new file addition. */
        public static FileChange added(String path, int lines) {
            return new FileChange(path, ChangeType.ADDED, lines, 0);
        }

        /** Creates a new file modification. */
        public static FileChange modified(String path, int added, int removed) {
            return new FileChange(path, ChangeType.MODIFIED, added, removed);
        }

        /** Creates a file deletion. */
        public static FileChange deleted(String path, int lines) {
            return new FileChange(path, ChangeType.DELETED, 0, lines);
        }

        /** Creates a file rename. */
        public static FileChange renamed(String path) {
            return new FileChange(path, ChangeType.RENAMED, 0, 0);
        }
    }
}
